// This file is auto generated by `nuxt prepare`
// Please do not manually modify this file.

/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@nuxt/content" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/components" />
export {}
